spring:
  application:
    name: Manage-Service
  main:
    allow-bean-definition-overriding: true #设置为true，表示后发现的bean会覆盖之前相同名称的bean。
server:
  port: 8201

eureka:
  client:
    register-with-eureka: true #向eureka注册服务
    fetch-registry: true #获取注册服务信息
    instance-info-replication-interval-seconds: 30  #新实例信息变化到服务端时间（秒）
    registry-fetch-interval-seconds: 3 #每3秒获取服务信息并缓存，默认30秒
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

sharding:
  jdbc:
    datasource:
      names: db0,db1
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 使用新版本驱动，则要指定区时serverTimezone
        jdbc-url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    # 水平拆分的数据库（表） 配置分库 + 分表策略 行表达式分片策略
    # 分库策略
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: db$->{id %2}
        # 分表策略 其中user为逻辑表 分表主要取决于age字段
        tables:
          user:
            actual-data-nodes: db$->{0..1}.user_$->{0..1}
            table-strategy:
              inline:
                sharding-column: age
                algorithm-expression: user_$->{age %2} # 分片算法表达式
            key-generator-column-name: id
      #打印执行的数据库以及语句
      props:
        sql:
          show: true
#mybatis-plus映射mapper文件
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.open.manageservice.entity
